import { getSql } from "@/lib/db";

export async function ensureBlastTables() {
  const sql = getSql();
  await sql.query(`
    CREATE TABLE IF NOT EXISTS text_blasts (
      id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      body text NOT NULL,
      status text NOT NULL DEFAULT 'draft',
      provider text,
      recipient_count integer NOT NULL DEFAULT 0,
      sent_count integer NOT NULL DEFAULT 0,
      failed_count integer NOT NULL DEFAULT 0,
      filter_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
      created_at timestamptz NOT NULL DEFAULT now()
    )
  `);
  await sql.query(`
    CREATE TABLE IF NOT EXISTS text_blast_recipients (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      blast_id uuid NOT NULL REFERENCES text_blasts(id) ON DELETE CASCADE,
      alumni_id uuid REFERENCES alumni(id) ON DELETE SET NULL,
      name text,
      phone text NOT NULL,
      status text NOT NULL DEFAULT 'pending',
      error text,
      created_at timestamptz NOT NULL DEFAULT now()
    )
  `);
  await sql.query(`
    CREATE TABLE IF NOT EXISTS email_blasts (
      id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      subject text NOT NULL,
      body text NOT NULL,
      status text NOT NULL DEFAULT 'draft',
      provider text,
      recipient_count integer NOT NULL DEFAULT 0,
      sent_count integer NOT NULL DEFAULT 0,
      failed_count integer NOT NULL DEFAULT 0,
      filter_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
      created_at timestamptz NOT NULL DEFAULT now()
    )
  `);
  await sql.query(`
    CREATE TABLE IF NOT EXISTS email_blast_recipients (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      blast_id uuid NOT NULL REFERENCES email_blasts(id) ON DELETE CASCADE,
      alumni_id uuid REFERENCES alumni(id) ON DELETE SET NULL,
      name text,
      email text NOT NULL,
      status text NOT NULL DEFAULT 'pending',
      error text,
      created_at timestamptz NOT NULL DEFAULT now()
    )
  `);
}
